title: TEAMSECOND Tech Blog
subtitle: CUBRID DBMS Engine Developers
description: >- # this means to ignore newlines until "baseurl:"
  TBD
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

permalink: /:categories/:title:output_ext

author_logo: cubrid-logo.png
disqus_shortname: ts-dev  #for comments using disqus
author: teamsecond
author_bio: ""
author_email: "dev2@cubrid.com"
author_location: South Korea
author_website_url: "https://www.cubrid.com/"

plugins: [jekyll-feed, jekyll-sitemap, jekyll-codepen, jekyll-assets, bootstrap, autoprefixer-rails]

exclude: 
  - vendor
  - "Gemfile*"
  - "Rakefile"
  - "*.sh"
  - "*.bat"
  - .travis.yml
  - README.md

markdown: kramdown
highlighter: rouge

codepen:
  theme: 11473
  height: 300
  preview: false
  default_tab: result

kramdown:
  input: GFM
  syntax_highlighter: rouge
